### ISSUE TITLE
Invitation...

### ISSUE THREAD

**Issue by mamarilmanson** [TheHX/leveleditor#1]
Hello...I have observed most of the pull request you have on godot is regarding the UI...

 we (just me and a fellow godot user) are planning on rewriting and cleaning the godot ui... and possibly forking and rebrand it... We would like to ask for you help if it is ok with you... 

I apologize if this is the only place where I can send you a message... :)

**Comment by TheHX** [comment]
Sorry for the late reply. I'm interested in this, you guys already have something planned? 

Oh, and you could send me a e-mail, it's on my github profile.

**Comment by mamarilmanson** [comment]
We are actually planning on forking and porting godot to qt ui... I'll shoot an email once I get more details after announcing that you have answered the call... 

Thank you very much! please do keep in touch... :D

**Comment by mamarilmanson** [comment]
anyway? as an (informal, friendly; I'm just saying it in a formal manner) interview question:

what do you say about the godot's current ui? please be honest as you can... :D

**Comment by TheHX** [comment]
To be simple, i really like Godot UI, i don't like much the current theme or the editor ui. And i want help on modernizing Godot UI, but porting to Qt does not appear to be the ideal to me at this moment.

**Comment by mamarilmanson** [comment]
ok... thank you for the answer... why we are planning this is because after mike's (not from gamesfromscratch) though the code, he noticed that the code was not clean... and in my case, modernizing the UI is very good... but at this moment it seems that features are being hacked in instead of being integrated... one example was there was one contributor that would like to implement a feature but was hindered by the code's lack of other feature that might support the code he wants to implement... that's our side of the case... I hope you understand... :)

**Comment by mamarilmanson** [comment]
Have you received the email? :)

**Comment by TheHX** [comment]
Yes i received one, sorry for not reply, i'm waiting more info about the 
project.

**Comment by mamarilmanson** [comment]
Oh... ok... I also apologize if no one is replying... our main man is busy about the (spoiler) new wed life... :)

**Comment by mamarilmanson** [comment]
A reply has been sent... :)

**Comment by TheHX** [comment]
Huh... i only have received this message.

Em 19-08-2015 09:51, Manson Mamaril escreveu:

**Comment by mamarilmanson** [comment]
now I have sent the mail... it seems Mike only replied to me by mistake... :)
